### ISSUE TITLE
New pandoc version

### ISSUE THREAD

**Issue by redadmiral** [jez/pandoc-sidenote#15]
Since I updated pandoc to version 2.10 `pandoc-sidenote` gives me the following error:

```
pandoc-sidenote: Error in $: Incompatible API versions: encoded with [1,21] but attempted to decode with [1,20].
CallStack (from HasCallStack):
  error, called at ./Text/Pandoc/JSON.hs:107:64 in pandoc-types-1.20-Azr3zp3CsDMiPqJ5OI8N8:Text.Pandoc.JSON
Error running filter pandoc-sidenote:
Filter returned error status 1
```
pandoc version:

```
pandoc --version
pandoc 2.10.1
Compiled with pandoc-types 1.21, texmath 0.12.0.2, skylighting 0.8.5
Default user data directory: /home/marco/.local/share/pandoc or /home/marco/.pandoc
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```
I'm aware that sidenote is built against a specific version and 2.10 is none of them, but nevertheless I'd be very happy if you could make sidenote work with the newest pandoc version. Downgrading and locking all those haskell packages is no fun at all and probably would cause further distress when trying to run other programs depending on those packages.

Thank you very much for developing this filter – I really enjoy writing excerpts and academical notes using it :heart:

**Comment by jeremycherfas** [comment]
I've only just started to explore sidenotes rather than endnotes, and upgraded pandoc as the first step, without realising that it would no longer be compatible. I too hope you will make a version that works with pandoc 2.10.1

Thank you.

**Comment by j-rostand** [comment]
Same issue here! 
Will pandoc-sidenote remain tied to a specific pandoc version in the future ?
Thanks for your great work anyway.

**Comment by ngirard** [comment]
I'm affected by this as well...
Cheers

**Comment by wowo101** [comment]
I get a very similar error with pandoc-ruby 2.1.7:

`pandoc-sidenote: Error in $: Incompatible API versions: encoded with [1,23] but attempted to decode with [1,22]`

Any immediate tips or pointers? Any additional information you need to analyse this?
