### ISSUE TITLE
Support for scoop package manager done ✅ 

### ISSUE THREAD

**Issue by arnos-stuff** [jez/pandoc-sidenote#25]
Hi everyone,

I managed to add your package to the [scoop package manager](https://scoop.sh), which auto installs all the dependencies such as

* haskell
* stack
* 7zip

Just with this **one-liner** you can install the exe 👍 

```powershell
scoop install https://gist.githubusercontent.com/arnos-stuff/1e6fb8c1049c44ff088946c124c764f4/raw/e0fd7e9fda71f9e648d161bc82bbce9dffe9a1cc/pandoc-sidenotes.json
```

With a little extra work we could add it to a [scoop bucket](https://scoop.sh/#/buckets) and avoid the ugly raw gist url 😅

**Comment by jez** [comment]
Thanks for the heads up
